version: "3.3"
services:
    back:
        image: "python:3.11"
        build:
            context: ./back
            dockerfile: Dockerfile
        container_name: back
        ports:
            - "26601:26601"

    front:
        container_name: front
        build:
            context: ./front
            dockerfile: Dockerfile

        environment:
            - HOST=http://78.40.188.96:26601
            - NODE_ENV=development
            - NEXT_TELEMETRY_DISABLED=1

        depends_on:
            - back

        restart: always

        ports:
            - "26600:26600"
